# Generated by Django 3.2.4 on 2021-06-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='occupants_count',
        ),
    ]
