# Generated by Django 3.2.4 on 2021-06-05 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0003_rename_neighborhoud_business_neighbourhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='neighborhood',
            new_name='neighbourhood',
        ),
    ]
