# Generated by Django 3.2.4 on 2021-06-05 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborapp', '0004_rename_neighborhood_user_neighbourhood'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Profile',
        ),
    ]
